# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mc352UThNcDjnnB0il2F4nSYE36wTYv2
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Load model
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("/content/drive/MyDrive/Colab Notebooks/Dataset (CPE32S3)/bird_drone_classifier.h5")
    return model

model = load_model()

# Title
st.title("Bird vs Drone Classifier")
st.write("Upload an image to classify it as a **bird** or a **drone**.")

# File uploader
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocessing
    image = image.resize((150, 150))
    img_array = np.expand_dims(np.array(image) / 255.0, axis=0)

    # Prediction
    prediction = model.predict(img_array)[0][0]
    label = "Drone" if prediction > 0.5 else "Bird"
    confidence = prediction if prediction > 0.5 else 1 - prediction

    # Output
    st.markdown(f"### Prediction: `{label}`")
    st.markdown(f"### Confidence: `{confidence:.2f}`")